---
apiVersion: v1
kind: Pod
metadata:
  - name: multi
specs:
  - name: nginx
    Image: nginx
    ports:
      - containerPort: 80
  - name: almalimux
    image: almalinux
    command: ["sleep", "100"]