apiVersion: v1
kind: Pod
metadata:
  name: label
  labels:
    course: docker
    duration: 25hr
    trainer: siva
  annotations:
    org.docker.kubernetes.image.maintainer: siva
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerport: 80
