apiVersion: v1
kind: Pod
metadata:
  name: env
specs:
  containers:
    -name: nginx
     image: nginx
     env:
      - name: course
        value: docker
      - name: trainer
        value: siva
      