apiVersion: v1
kind: Pod
metadata:
  name: config-pod
specs:
  containers:
    -name: nginx
     image: nginx
     env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: course
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: duration
       