---
apiVersion: v1
kind: Pod
metadata:
  server: nginx
specs:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerport: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    service: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
